name: Data Converter Build Workflow

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * 0'  # Raz w tygodniu w niedzielę o północy
  workflow_dispatch:     # Ręczne uruchomienie

jobs:
  build:
    runs-on: macos-latest  # Domyślny serwer dla Maca
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies (Mac)
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller PyQt5 pyyaml xmltodict
        
    - name: Run installResources.ps1 (Mac compatible)
      shell: bash
      run: |
        chmod +x ./installResources.ps1
        ./installResources.ps1
        
    - name: Build console version
      run: |
        pyinstaller --onefile converter.py
        
    - name: Build GUI version
      run: |
        pyinstaller --onefile --windowed converter_ui.py
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: macos-build
        path: |
          dist/converter
          dist/converter_ui
